#!/usr/bin/env python3

# this is a script to create / manage / run other scripts that filter stdin and
# return to stdout


import os
import sys


def main():
    if len(sys.argv) < 2:
        msg = (
            'ERROR: fltr: no arguments passed\n\n'
            'usage:\n'
            '  fltr [command]? [filter]\n\n'
            '  commands:\n'
            '    run    - run a fltr named [filter]\n'
            '             this is the default when no command is passed\n'
            '    create - create a new fltr named [filter]\n'
            '    list   - lists out all the fltrs\n'
            '    edit   - edit a fltr named [filter]\n'
            '    remove - remove a fltr named [filter]\n'
        )
        print(msg, file = sys.stderr)
        sys.exit(1)

    # check stdin
    stdin = None
    if not sys.stdin.isatty():
        stdin = []
        for line in sys.stdin: stdin += [line.rstrip()]

    match sys.argv[1]:
        case 'list':
            (err, fltrs) = list_fltrs(sys.argv[1:])
            if err:
                msg = (
                    f'ERROR: fltr list: {fltrs}\n\n'
                    'usage:\n'
                    '  fltr list\n\n'
                    '  lists out all of the fltr scripts\n'
                )
                print(msg, file = sys.stderr)
                sys.exit(err)

            if len(fltrs) < 1:
                print('fltr list: no fltrs found in ~/.scripts/filters')
            else:
                for fltr in fltrs: print(fltr)

            sys.exit(0)

        case 'create':
            (err, err_msg) = create_fltr(sys.argv[1:])
            if err:
                msg = (
                    f'ERROR: fltr create: {err_msg}\n\n'
                    'usage:\n'
                    '  fltr create [filter] [editor]?\n\n'
                    '  creates a fltr named [filter] and enters [editor]\n'
                    '  the default command for [editor] is whatever $EDITOR is'
                )
                print(msg, file = sys.stderr)
                sys.exit(err)

            sys.exit(0)

        case 'edit':
            (err, err_msg) = edit_fltr(sys.argv[1:])
            if err:
                msg = (
                    f'ERROR: fltr edit: {err_msg}\n\n'
                    'usage:\n'
                    '  fltr edit [filter] [editor]?\n'
                    '  opens the file for [filter] in [editor]\n'
                    '  the default command for [editor] is whatever $EDITOR is'
                )
                print(msg, file = sys.stderr)
                sys.exit(err)

            sys.exit(0)

        case 'remove':
            (err, err_msg) = remove_fltr(sys.argv[1:])
            if err:
                msg = (
                    f'ERROR: fltr remove: {err_msg}\n\n'
                    'usage:\n'
                    '  fltr remove [filter]\n'
                    '  deletes the file for [filter]\n'
                )
                print(msg, file = sys.stderr)
                sys.exit(err)

            sys.exit(0)

        case 'run': run_fltr()
        case _: run_fltr()


def list_fltrs(args):
    if len(args) > 1: return (1, f'unknown extra arguments: {args[1:]}')
    try: files = os.listdir(os.path.expanduser('~/.scripts/filters'))
    except OSError as e: return(e.errno, f'{str(e)}')
    except Exception as e: return(1, f'{str(e)}')
    return (False, files)


def create_fltr(args):
    if len(args) < 2: return(1, f'no fltr name specified')
    if len(args) > 3: return(1, f'unknown extra arguments: {args[1:]}')
    (err, fltrs) = list_fltrs([])
    if err: return(err, fltrs)
    if args[1] in fltrs: return(17, f'fltr "{args[1]}" already exists')

    if args[1] in ['run', 'list', 'create', 'edit', 'remove']: return(1, 'cannot use command name as name for fltr')

    editor = '$EDITOR'
    if len(args) == 3: editor = args[2]

    os.system(f'touch ~/.scripts/filters/{args[1]}')
    os.system(f'{editor} ~/.scripts/filters/{args[1]}')
    os.system(f'chmod +x ~/.scripts/filters/{args[1]}')

    return (None, None)


def edit_fltr(args):
    if len(args) < 2: return(1, f'no fltr name specified')
    if len(args) > 3: return(1, f'unknown extra arguments: {args[1:]}')
    (err, fltrs) = list_fltrs([])
    if err: return(err, fltrs)
    if args[1] not in fltrs: return(2, f'fltr "{args[1]}" does not exist')

    editor = '$EDITOR'
    if len(args) == 3: editor = args[2]
    os.system(f'{editor} ~/.scripts/filters/{args[1]}')

    return (None, None)


def remove_fltr(args):
    if len(args) < 2: return(1, f'no fltr name specified')
    if len(args) > 2: return(1, f'unknown extra arguments: {args[1:]}')
    (err, fltrs) = list_fltrs([])
    if err: return(err, fltrs)
    if args[1] not in fltrs: return(2, f'fltr "{args[1]}" does not exist')

    confirm = input(f'fltr remove: delete the filter "{args[1]}"? ')
    if confirm.lower() not in ['y', 'ye', 'yes']: return(None, None)
    os.system(f'rm ~/.scripts/filters/{args[1]}')

    return (None, None)


def run_fltr(): pass


if __name__ == '__main__':
    main()
